// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AnalyzeData, AnalyzeErrors, AnalyzeResponses, CheckData, CheckErrors, CheckResponses, IgnoreData, IgnoreErrors, IgnoreResponses, ImportData, ImportErrors, ImportResponses, UpgradeData, UpgradeErrors, UpgradeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class MigrationsService {
    public static analyze<ThrowOnError extends boolean = false>(options?: Options<AnalyzeData, ThrowOnError>) {
        return (options?.client ?? client).post<AnalyzeResponses, AnalyzeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/usync-migrations/api/v1/analyze',
            ...options
        });
    }
    
    public static check<ThrowOnError extends boolean = false>(options?: Options<CheckData, ThrowOnError>) {
        return (options?.client ?? client).get<CheckResponses, CheckErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/usync-migrations/api/v1/check',
            ...options
        });
    }
    
    public static ignore<ThrowOnError extends boolean = false>(options?: Options<IgnoreData, ThrowOnError>) {
        return (options?.client ?? client).post<IgnoreResponses, IgnoreErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/usync-migrations/api/v1/ignore',
            ...options
        });
    }
    
    public static import<ThrowOnError extends boolean = false>(options?: Options<ImportData, ThrowOnError>) {
        return (options?.client ?? client).post<ImportResponses, ImportErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/usync-migrations/api/v1/import',
            ...options
        });
    }
    
    public static upgrade<ThrowOnError extends boolean = false>(options?: Options<UpgradeData, ThrowOnError>) {
        return (options?.client ?? client).post<UpgradeResponses, UpgradeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/usync-migrations/api/v1/upgrade',
            ...options
        });
    }
}
