// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44349' | (string & {});
};

export type SyncUpgradeCheckResponse = {
    hasLegacyFolder: boolean;
    legacyFolderPath?: string | null;
    lagacyTypes: Array<string>;
    lastestFolder: string;
    latestVersion: string;
};

export type SyncUpgradeMessage = {
    status: SyncUpgradeStatus;
    upgrader: string;
    fileName: string;
    message?: string | null;
};

export type SyncUpgradeStatus = 'Info' | 'Success' | 'Warning' | 'Error';

export type AnalyzeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync-migrations/api/v1/analyze';
};

export type AnalyzeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AnalyzeResponses = {
    /**
     * OK
     */
    200: Array<SyncUpgradeMessage>;
};

export type AnalyzeResponse = AnalyzeResponses[keyof AnalyzeResponses];

export type CheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync-migrations/api/v1/check';
};

export type CheckErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CheckResponses = {
    /**
     * OK
     */
    200: SyncUpgradeCheckResponse;
};

export type CheckResponse = CheckResponses[keyof CheckResponses];

export type IgnoreData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync-migrations/api/v1/ignore';
};

export type IgnoreErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type IgnoreResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ImportData = {
    body?: never;
    path?: never;
    query?: {
        clientId?: string;
    };
    url: '/umbraco/usync-migrations/api/v1/import';
};

export type ImportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpgradeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync-migrations/api/v1/upgrade';
};

export type UpgradeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UpgradeResponses = {
    /**
     * OK
     */
    200: Array<SyncUpgradeMessage>;
};

export type UpgradeResponse = UpgradeResponses[keyof UpgradeResponses];
